apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}

  artifacts:
  - context: server
    image: model-server
  - context: app
    image: apogee-app

# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - manifests/**

# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
